# deletar livro por id
DELETE http://localhost:8080/livros/1

###

# create livro com categoria
POST http://localhost:8080/livros?categoria=1
Content-Type: application/json

{
  "titulo": "Teste",
  "nomeAutor": "teste",
  "texto": "teste"
}

###

# atualizar livro parcial
PATCH http://localhost:8080/livros
Content-Type: application/json

{
  "id": 1,
  "titulo": "a",
  "nomeAutor": "teste",
  "texto": "teste"
}

###
# atualizar livro inteiro
PUT http://localhost:8080/livros
Content-Type: application/json

{
  "id": 1,
  "titulo": "teste",
  "nomeAutor": "teste",
  "texto": "teste"
}

###
# listar livros por id de categoria
GET http://localhost:8080/livros?categoria=1

###
# listar livros por id
GET http://localhost:8080/livros/1

###
# deletar categoria por id
DELETE http://localhost:8080/categorias/1

###

# atualizar categoria por id
PUT http://localhost:8080/categorias
Content-Type: application/json

{
  "id": 1,
  "nome": "Teste",
  "descricao": "Livro Teste"
}

###
# listar todas as categorias com livros
GET http://localhost:8080/categorias/

###
# listar categoria por id
GET http://localhost:8080/categorias/1

###
# listar categoria por id
POST http://localhost:8080/categorias
Content-Type: application/json

{
  "id": 1,
  "nome": "Teste",
  "descricao": "Livro Teste"
}

###
